[build]
  publish = "public"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Optional: Configure redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
